version: "3.8"

services:
  media-reciever-production:
    container_name: media-reciever-production
    build:
      target: production
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"

  media-reciever-dev:
    container_name: media-reciever-dev
    restart: unless-stopped
    env_file: .env
    build:
      target: dev
      context: .
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"
    volumes:
      - .:/media-reciever-app
      - node_modules:/media-reciever-app/node_modules/
    command: npm run start:debug # override entry command

volumes:
  node_modules: